version: '3.2'

services:
    first:
        build: ./first-react-app
        container_name: first
        ports:
            - "8001:3000"
        restart: always

    second:
        build: ./second-react-app
        container_name: second
        ports:
            - "8002:3000"
        restart: always

    third:
        build: ./third-react-app
        container_name: third
        ports:
            - "8003:3000"
        restart: always